# Generated by Django 4.0.1 on 2022-01-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Unknown', unique=True, verbose_name='Nama Lokasi')),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_name', models.TextField(default='Unknown', unique=True, verbose_name='Nama Wisata')),
                ('dest_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.locations', verbose_name='Lokasi Wisata')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_desc', models.TextField(null=True, verbose_name='Deskripsi')),
                ('dest_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.destinations', verbose_name='Nama Wisata')),
            ],
        ),
    ]
