# Generated by Django 4.0.1 on 2022-01-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='dest_name',
            field=models.CharField(default='Unknown', max_length=225, unique=True, verbose_name='Nama Wisata'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(default='Unknown', max_length=225, unique=True, verbose_name='Nama Lokasi'),
        ),
    ]
